CONTAINER Oshrinkwrap
{
	NAME Oshrinkwrap;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LINK SHRINKWRAP_TARGET_LINK
		{
			ACCEPT
			{
				Obase;
			}
			REFUSE
			{
				Osky;
				Oforeground;
			}
		}

		BOOL SHRINKWRAP_USE_SUBDIV { }

		LONG SHRINKWRAP_MODE
		{
			CYCLE
			{
				SHRINKWRAP_MODE_NEAREST_SURFACE;
				SHRINKWRAP_MODE_PROJECT;
				SHRINKWRAP_MODE_NEAREST_VERTEX;
				SHRINKWRAP_MODE_TARGET_NORMAL;
			}
		}

		BOOL SHRINKWRAP_SNAP_VERTICES_EDGES { }
		BOOL SHRINKWRAP_IGNORE_CAMERA { }

		SEPARATOR { LINE; }

		REAL SHRINKWRAP_OFFSET { UNIT METER; STEP 0.1; }
		REAL SHRINKWRAP_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL SHRINKWRAP_FALLOFF_RADIUS { UNIT METER; MIN 0.0; }

		SEPARATOR { LINE; }

		BOOL SHRINKWRAP_BIDIRECTIONAL { }
		BOOL SHRINKWRAP_ABOVE_SURFACE { }

		SEPARATOR { LINE; }

		LINK SHRINKWRAP_VERTEXMAP_LINK
		{
			ACCEPT
			{
				5682;
			}
		}

		LINK SHRINKWRAP_EXCLUDE_SELECTION_LINK
		{
			ACCEPT
			{
				5674;
				5673;
				5701;
				5682;
			}
		}

		SEPARATOR { LINE; }

		BOOL SHRINKWRAP_AUTO_BAKE { }

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;
			BUTTON SHRINKWRAP_ENABLE_DEFORMED_EDITING { }
			BUTTON SHRINKWRAP_APPLY_TO_MESH { }
		}

		SEPARATOR { LINE; }

		GROUP SHRINKWRAP_GROUP_DISPLAY
		{
			DEFAULT 1;

			BOOL  SHRINKWRAP_ENABLE_CUSTOM_COLOR { }
			COLOR SHRINKWRAP_MESH_COLOR          { }
			REAL  SHRINKWRAP_FACE_OPACITY        { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			BOOL  SHRINKWRAP_DRAW_WIREFRAME      { }
			COLOR SHRINKWRAP_WIRE_COLOR          { }
			REAL  SHRINKWRAP_WIRE_WIDTH          { MIN 1.0; MAX 10.0; MINSLIDER 1.0; MAXSLIDER 5.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		}
	}
}
