#ifndef OSHRINKWRAP_H__
#define OSHRINKWRAP_H__

enum
{
	SHRINKWRAP_TARGET_LINK				= 1000,
	SHRINKWRAP_MODE						= 1001,
	SHRINKWRAP_OFFSET					= 1002,
	SHRINKWRAP_STRENGTH					= 1003,
	SHRINKWRAP_FALLOFF_RADIUS			= 1004,
	SHRINKWRAP_BIDIRECTIONAL			= 1005,
	SHRINKWRAP_ABOVE_SURFACE			= 1006,
	SHRINKWRAP_VERTEXMAP_LINK			= 1007,
	SHRINKWRAP_ENABLE_DEFORMED_EDITING	= 1008,
	SHRINKWRAP_APPLY_TO_MESH			= 1009,
	SHRINKWRAP_AUTO_BAKE				= 1010,

	// Display settings (matching C4D_QuadDraw style)
	SHRINKWRAP_GROUP_DISPLAY			= 1020,
	SHRINKWRAP_ENABLE_CUSTOM_COLOR		= 1021,
	SHRINKWRAP_MESH_COLOR				= 1022,
	SHRINKWRAP_MESH_XRAY				= 1023,
	SHRINKWRAP_DRAW_WIREFRAME			= 1024,
	SHRINKWRAP_WIRE_COLOR				= 1025,
	SHRINKWRAP_WIRE_WIDTH				= 1026,

	// Values for SHRINKWRAP_MODE cycle
	SHRINKWRAP_MODE_NEAREST_SURFACE		= 0,
	SHRINKWRAP_MODE_PROJECT				= 1,
	SHRINKWRAP_MODE_NEAREST_VERTEX		= 2,
	SHRINKWRAP_MODE_TARGET_NORMAL		= 3
};

#endif // OSHRINKWRAP_H__
